name: GitHub Actions Demo
on:
  push:
    paths-ignore:
      - ".github"
    branches: 
      - main
  pull_request:
    branches: [main]
  schedule:
    - cron: "15 6 * * SUN"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Name of trigger
        run: echo ${{ github.event_name }}
    
